name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up python
      id: setup-python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.3'

    - name: Install and configure Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.5.1
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true

    - name: Install dependencies
      run: poetry install

    - name: Run make all inside Poetry shell
      run: poetry run make

    - name: Check ACT environment variable
      id: check_act
      run: echo "::set-output name=act_not_set::${{ env.ACT == '' }}"

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: release
        path: release/*

  release:
    if: github.event_name == 'push' && needs.build.outputs.act_not_set == 'true'
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Download artifacts
      uses: actions/download-artifact@v4.1.7
      with:
        name: release

    - uses: ncipollo/release-action@v1
      with:
        artifacts: "release/*"
        tag: ${{ github.run_number }}
        token: ${{ secrets.GITHUB_TOKEN }}

    - uses: dev-drprasad/delete-older-releases@v0.1.0
      with:
        keep_latest: 3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
